[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/yahoo/*"
  to = "/.netlify/functions/yahoo/y/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/custom-yahoo/*"
  to = "/.netlify/functions/yahoo/c/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/search/*"
  to = "/.netlify/functions/yahoo/s/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
